branches:
  only:
    - develop
    - master

language: php

php: 
  - 7.2
  - 7.3
  - 7.4

matrix:
  allow_failures:
    - php: 7.2
      env: COMPOSER_ARGS="--prefer-lowest"

env:
 - COMPOSER_REQS="laravel/framework:>=5.7"
  matrix:
    exclude:
    # laravel 5.5 and higher only supports php 7
    - php: 5.6
      env: COMPOSER_REQS="laravel/framework:>=5.7"

install:
  - composer require --no-update $COMPOSER_REQS
  - composer update ${COMPOSER_ARGS} --no-interaction

script:
  - vendor/bin/phpunit --verbose

sudo: false
